market_id: cme_es
venue_tz: America/Chicago

weekly:
  - days: [Sun]
    windows:
      - { start: "17:00", end: "23:59:59", label: "ETH" }

  - days: [Mon, Tue, Wed, Thu]
    windows:
      - { start: "00:00", end: "08:29:59", label: "ETH" }
      - { start: "08:30", end: "15:00",    label: "RTH" }
      - { start: "15:00", end: "16:00",    label: "POST" }
      - { start: "17:00", end: "23:59:59", label: "ETH" }

  - days: [Fri]
    windows:
      - { start: "00:00", end: "15:00", label: "RTH" }
      # You can uncomment POST if you prefer to show it 15:00–16:00
      # - { start: "15:00", end: "16:00", label: "POST" }

maintenance:
  - { days: [Mon, Tue, Wed, Thu], start: "16:00", end: "17:00" }

weekend_close:
  friday_close: "16:00"
  sunday_reopen: "17:00"

labels:
  closed_reason_weekend: "WEEKEND"
  closed_reason_maintenance: "MAINTENANCE"

holidays:
  # Seed a few; extend later or replace with a generated list
  - "2025-01-01"
  - "2025-01-20"
  - "2025-02-17"

early_closes:
  # Example: uncomment to test an early close day
  # "2025-07-03": { rth_end: "12:15", label: "EARLY_CLOSE" }

